apiVersion: apps/v1
kind: Deployment
metadata:
 name: lbg-api
 labels:
  app: node-app
  env: prod
spec:
 template:
   metadata:
     labels:
       app: node-pod
   spec:
   containers:
   - name: node-container
     image: gcr.io/lbg-210322/hello_yem:v1
     ports:
     - containerPort: 5000
     env:
     - name: PORT
       value: "5000"
 replicas: 2
 selector:
   matchLabels:
     app: node-pod
 strategy:
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25
